vich_uploader:
    db_driver: orm

    mappings:
        profil_picture:
            uri_prefix: /images/profil_picture
            upload_destination: '%kernel.project_dir%/public/images/profil_picture'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        
        club_picture:
            uri_prefix: /images/club_picture
            upload_destination: '%kernel.project_dir%/public/images/club_picture'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
